language: java

addons:
  sonarqube:
    token:
      secure: "36e1a1433f7c1425a362704ce26accb67d82ac72"
jdk:
  - oraclejdk8
  
install: mvn clean install  sonar:sonar -Dsonar.host.url=https://sonarqube.com  -Dsonar.login=36e1a1433f7c1425a362704ce26accb67d82ac72
script: mvn test 


cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'

notifications:
  email: false

